let ognKeyboardShortcuts = {
    '!':{action:'selectTool', args:{tool:'draw'}},
    ':':{action:'selectTool', args:{tool:'erease'}},
    ';':{action:'selectTool', args:{tool:'move'}},
    'u':{action:'elementMoveBackward'},
    'j':{action:'elementMoveForward'},
    'y':{action:'elementCopy'},
    'h':{action:'elementPaste'},
    'b':{action:'layerDel'},
    'v':{action:'drawingClear'},
    'c':{action:'elementDel'},
    'f':{action:'elementAddCellAfter'},
    'r':{action:'elementAddCellBefore'},
    'e':{action:'navigationFirstFrm'},
    'd':{action:'navigationLastFrm'},
    'z':{action:'navigationPrevFrm'},
    's':{action:'navigationNextFrm'},
    'a':{action:'navigationAutoRun'},
    'q':{action:'navigationPlay'},
}